# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cd8a7647107628f42619418e5ef08249c3852b07d831ab0f6f02b70ec5296dfcf1405f58ebd1cedc4a6ada0c66095c6521bb3994dbeba99f8684b4a51de8666b

test:
  secret_key_base: 80e348176d14aeace54ffe192e2c076e37f9381f6b3f270cef5f4047d7f72ae8fa2f4fea49f8e211e7d9af5a74e5b9f938cd21149e896c54bcd5a085cdd1a212

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
